name: forum-microservices
version: '3'
services:

  apigateway_webserver:
    image: nginx:alpine
    container_name: apigateway_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9000:80"
    volumes:
      - ./apps/apigateway/:/var/www/apigateway
      - ./docker/nginx/confs/apigateway_nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/apigateway/:/etc/nginx/conf.d/
    networks:
      - app-network

  apigateway:
    build:
      context: apps/apigateway
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: apigateway
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: apigateway
      SERVICE_TAGS: dev
    working_dir: /var/www/apigateway
    volumes:
      - ./apps/apigateway/:/var/www/apigateway
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - apigateway_db
    depends_on:
      - apigateway_webserver
    networks:
      - app-network

  apigateway_db:
    image: mysql:8.0
    container_name: apigateway_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: forum_microservice
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_HOST: apigateway_db
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_NAME: apigateway_db
      SERVICE_TAGS: dev
    volumes:
      - apigateway-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - apigateway

  postservice_webserver:
    image: nginx:alpine
    container_name: postservice_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9001:80"
    volumes:
      - ./apps/postservice/:/var/www/postservice
      - ./docker/nginx/confs/postservice_nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/postservice/:/etc/nginx/conf.d/
    depends_on:
      - apigateway_db
    networks:
      - app-network

  postservice:
    build:
      context: apps/postservice
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: postservice
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: postservice
      SERVICE_TAGS: dev
    working_dir: /var/www/postservice
    volumes:
      - ./apps/postservice/:/var/www/postservice
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postservice_webserver
    networks:
      - app-network

  commentservice_webserver:
    image: nginx:alpine
    container_name: commentservice_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9002:80"
    volumes:
      - ./apps/commentservice/:/var/www/commentservice
      - ./docker/nginx/confs/commentservice_nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/commentservice/:/etc/nginx/conf.d/
    depends_on:
      - postservice
    networks:
      - app-network

  commentservice:
    build:
      context: apps/commentservice
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: commentservice
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: commentservice
      SERVICE_TAGS: dev
    working_dir: /var/www/commentservice
    volumes:
      - ./apps/commentservice/:/var/www/commentservice
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - commentservice_webserver
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis-data:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    depends_on:
      - commentservice

networks:
  app-network:
    driver: bridge

volumes:
  apigateway-db:
    driver: local