name: APIGateway CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - uses: actions/checkout@v3

      - name: Install composer dependencies
        run: |
          cd apps/apigateway
          cp .env.example .env
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          mkdir -p database
          touch database/database.sqlite

      - name: Executed tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          cd apps/apigateway
          vendor/bin/phpunit
